name: Publish to NuGet
on:
  push:
    branches:
      - main  # Trigger the workflow on push to main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'  # Set up .NET version

    - name: Restore dependencies
      run: dotnet restore

    - name: Create Package
      run: sh Pack.sh

    - name: Push to NuGet
      run: dotnet nuget push out/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
